<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="ARPGL000810" name="com.qa.testcases.LoginPageTest" tests="9" failures="1" timestamp="2020-09-01T16:49:41 IST" time="182.266" errors="0">
  <testcase name="loginPageTitleTest" time="9.012" classname="com.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <system-out/>
  <testcase name="UITest" time="11.260" classname="com.qa.testcases.LoginPageTest"/>
  <system-out/>
  <testcase name="stdUserLoginTest" time="68.867" classname="com.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- stdUserLoginTest -->
  <system-out/>
  <testcase name="stdUserLoginTest" time="20.329" classname="com.qa.testcases.LoginPageTest"/>
  <system-out/>
  <testcase name="multiUserLoginTest" time="21.809" classname="com.qa.testcases.LoginPageTest"/>
  <system-out/>
  <testcase name="multiUserLoginTest" time="18.611" classname="com.qa.testcases.LoginPageTest"/>
  <system-out/>
  <testcase name="multiUserLoginTest" time="12.930" classname="com.qa.testcases.LoginPageTest"/>
  <system-out/>
  <testcase name="multiUserLoginTest" time="11.005" classname="com.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.qa.pages.ProductsPage.verifyPageByURL(ProductsPage.java:35)
at com.qa.testcases.LoginPageTest.multiUserLoginTest(LoginPageTest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- multiUserLoginTest -->
  <system-out/>
  <testcase name="multiUserLoginTest" time="8.443" classname="com.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- multiUserLoginTest -->
  <system-out/>
</testsuite> <!-- com.qa.testcases.LoginPageTest -->
